### PR TITLE
Add jackson-module-jakarta-xmlbind-annotations to docker category.xml

### PR DESCRIPTION
**Pull request by jjohnstn**

### CODE REVIEW

**Comment by jonahgraham** [comment]
Thanks @jjohnstn - with the change we can build CDT again AFAICT. But I need to merge in the change to consume 4.31 I-builds in the CDT target file.

**Comment by jonahgraham** [comment]
@jjohnstn the build you kicked off seems to have self cancelled? https://ci.eclipse.org/linuxtools/job/linuxtools/job/master/322/console can you start it again?

**Comment by jjohnstn** [comment]
@jonahgraham There was some issue with our Jenkins build as it kept stalling claiming things were off-line.  I cancelled a number of jobs but eventually got it to build and put our M3 into the aggregation.

**Comment by jonahgraham** [comment]
BTW I had a similar problem the other day and webmaster restarted jenkins instance and all has been stable since then.

**Pull request merged**
