### PR TITLE
Move JNR deps that are OSGi bundles to Maven central

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
unrelated test failures

**Comment by merks** [comment]
The orbit-simrel generator notices these changes and tries to compose them.  But it wants to test that all requirements resolve, so it notices missing requirements:

> [ERROR]   Missing requirement: com.github.jnr.enxio 0.32.15 requires 'java.package; com.kenai.jffi 0.0.0' but it could not be found

So I track that down to this:

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/

But also adding that I notice that it is not a bundle:

> Artifact com.github.jnr:jffi:1.3.11 is not a bundle and MissingManifestStrategy is set to error for this location

I'm not sure if that's the only dependency that's not a bundle...

**Comment by merks** [comment]
I guess you need all these still which all need wrapping:

> <unit id="com.github.jnr.a64asm" version="1.0.0.v20221215-1656"/>
> <unit id="com.github.jnr.jffi" version="1.3.9.v20221215-1656"/>
> <unit id="com.github.jnr.jffi.native" version="1.3.9.v20221215-1656"/>
> <unit id="com.github.jnr.x86asm" version="1.0.2.v20221112-0806"/>

I'm not sure where com.github.jnr.jffi.native comes from...

**Comment by akurtakov** [comment]
I preserved the old Orbit bundles for that in the target platform https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/master/releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target#L12 . I wonder what went wrong.

**Comment by akurtakov** [comment]
They are in the nightly repo https://download.eclipse.org/linuxtools/updates-docker-nightly/plugins/ too.

**Comment by merks** [comment]
Yes, all but jffi.native are needed by the things you've specified as `<dependency>`.    The other 3 things I've tracked down in Maven but I don't know where in Maven `com.github.jnr.jffi.native` comes from...

**Comment by akurtakov** [comment]
It's separate classifier in https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/

**Comment by merks** [comment]
I found that too, but not com.github.jnr.jffi.**native**  which is a separate Orbit bundle currently.

image

I'd expect to find it here

- https://repo1.maven.org/maven2/com/github/jnr/
- https://repo1.maven.org/maven2/com/github/jnr/jffi/

Oh, there are multiple jars here!

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/

That's interesting and tricky...

**Comment by akurtakov** [comment]
Ah I get it now, it's not that Linux Tools p2 repo is broken somehow but that the generator breaks.

**Comment by merks** [comment]
It's not even quite that.  It's just that the build process (after the generator updates correctly) tests that all dependencies transitively resolve.  I'm slowly starting to document this:

https://github.com/eclipse-orbit/orbit-simrel#readme

So then I think, ah, the missing things should be part of maven-bnd eventually, but for that too I need the Maven coordinates...

Anyway, I just wanted to track and document this, and then put it on the back burner for a while so that I can tackle it later...

**Comment by merks** [comment]
Unfortunately m2e and Tycho won't produce a bundle for a dependency with type native:
```
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.11</version>
          <type>native</type>
        </dependency>
```

image

Only type jar works:
```
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.11</version>
          <type>jar</type>
        </dependency>
```
image

I'm not sure if m2e and Tycho use the same underlying implementation or if this would need to be fixed twice, assuming there is a will for it to be fixed.  Failing that, we'd have to continue to use EBR for such a case.

**Comment by merks** [comment]
I was mistaken.  One needs to specify the classifier as native:
```
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.10</version>
          <type>jar</type>
          <classifier>native</classifier>
        </dependency>
```
Then I'm able to wrap all the com.github.jnr jars that are not bundles:

image

It gets a little confused if I put both in the same feature because I ask for source but I don't think that's makes sense for this native bundle...

**Comment by merks** [comment]
On closer analysis, this is an OSGi fragment

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11-native.jar

And I think this is its host OSGi bundle:

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11-complete.jar

**Comment by merks** [comment]
@akurtakov 

I believe you can  replace these orbit dependencies
```
<unit id="com.github.jnr.jffi" version="1.3.9.v20221215-1656"/>
<unit id="com.github.jnr.jffi.native" version="1.3.9.v20221215-1656"/>
```
with these two Maven dependencies:
```
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.11</version>
          <type>jar</type>
          <classifier>complete</classifier>
        </dependency>
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.11</version>
          <type>jar</type>
          <classifier>native</classifier>
        </dependency>
```
Note the version increase from 1.3.9 to 1.3.11.

These two dependencies need to be wrapped:
```
<unit id="com.github.jnr.a64asm" version="1.0.0.v20221215-1656"/>
<unit id="com.github.jnr.x86asm" version="1.0.2.v20221112-0806"/>
```

**Comment by merks** [comment]
New versions of the two dependencies that needs wrapping are available here:

- https://download.eclipse.org/tools/orbit/simrel/maven-bnd/nightly/latest
- https://download.eclipse.org/tools/orbit/simrel/maven-bnd/2023-09

If you add the two jffi things as dependencies, then I can delete this:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-osgi/tp/other/MavenSupplement.target#L152-L166

All the jnr Orbit dependencies you have now will be removed/replaced for 2023-09.

**Comment by akurtakov** [comment]
@merks But com.github.jnr.jffi is not OSGi bundle in Maven central so I think it should be wrapped too. 
Also is it fine to use [ttps://download.eclipse.org/tools/orbit/simrel/maven-bnd/2023-09](https://download.eclipse.org/tools/orbit/simrel/maven-bnd/2023-09) in build now to provide deps?

**Comment by merks** [comment]
I know there is a bunch of text above, but please note the **classifier** specifications here:
```
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.11</version>
          <type>jar</type>
          <classifier>complete</classifier>
        </dependency>
        <dependency>
          <groupId>com.github.jnr</groupId>
          <artifactId>jffi</artifactId>
          <version>1.3.11</version>
          <type>jar</type>
          <classifier>native</classifier>
        </dependency>
```

Here are links to the actual jars:

- https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11-complete.jar
- https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11-native.jar

You can verify these are OSGi bundles by looking at the MANIFEST.MF.

So you are correct that this is not a bundle, but this is not the jar being specified by the above classifier-qualified dependencies:

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11.jar

Yes, https://download.eclipse.org/tools/orbit/simrel/maven-bnd/2023-09 is a permanent new location.

But I still need to touch bases with @jonahgraham about URLs.

I suggest holding off until I finish that discussion.  I think you could change the two dependencies above now though and verify that those work properly...

**Comment by akurtakov** [comment]
Thanks, I totally missed the "complete" part. Will switch it today.

**Pull request merged**
