### PR TITLE
fix hamcrest resolution with Java17 and eclipse 4.25

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

Change-Id: I42f286bec8e5173441262b4f7b7e9850c7b77809

### CODE REVIEW

**Comment by sbouchet** [comment]
fixes #87

**Comment by akurtakov** [comment]
There are test failures with this commit that are not in master. Would you please investigate?

**Comment by sbouchet** [comment]
> There are test failures with this commit that are not in master. Would you please investigate?

ok, i'm reproducing locally. having difficult time because missing class is indeed present in hamcrest 1.3

**Comment by sbouchet** [comment]
drafting unitl tests passes.

**Comment by sbouchet** [comment]
@akurtakov : still struggling with the ClassNotFoundException [1] caused by mockito/junit/hamcrest. but at least the integration test bundle does not fails anymore to start ( current master branch builds do not fail even if the application cannot start ), see [2]. 
i may need some help here, because Junit 4.13 requires hamcrest.core 1.3 and mockito require hamcrest 2.2 and my tentative seems not working. 

[1]
```
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
	at org.eclipse.linuxtools.docker.integration.tests.ui.ComposeTest.setupDockerComposeUpMockProcess(ComposeTest.java:169)
	at org.eclipse.linuxtools.docker.integration.tests.ui.ComposeTest.before(ComposeTest.java:88)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing cannot be found by org.mockito.mockito-core_4.6.1
	at org.eclipse.linuxtools.docker.integration.tests.ui.ComposeTest.setupDockerComposeUpMockProcess(ComposeTest.java:169)
	at org.eclipse.linuxtools.docker.integration.tests.ui.ComposeTest.before(ComposeTest.java:88)
```

[2] 
```
java.lang.RuntimeException: Bundle org.eclipse.linuxtools.docker.integration.tests is not found
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundle(OsgiSurefireBooter.java:221)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundleClassLoader(OsgiSurefireBooter.java:197)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.createCombinedClassLoader(OsgiSurefireBooter.java:139)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:128)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:46)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] There are test failures.
````

**Comment by sbouchet** [comment]
finally made it, by using the correct mockito/assertj bundles from latest orbit.

**Comment by akurtakov** [comment]
Reverting to old versions of mockito,assertj,etc. are no-go as Eclipse Platform already ships these new versions in 4.25 so having multiple is just asking for problems as verifications buils shows (using 4.25 I-build).

**Comment by akurtakov** [comment]
To make it clear - Orbit will most likely not see many updates if at all for the dependencies that were brought there by Platform team thus it's recommended to rely on deps in Platform I-build or refer to maven coordinates directly. The former is easier the later is the way if newer version needed.

**Comment by akurtakov** [comment]
FWIW, if moving tests to Java 17 BREE would help please feel free to do so.

**Comment by sbouchet** [comment]
@akurtakov : i know that the new way is to use maven coordinates in target platform. I can provide a new PR using it in TP, but as  it will be the first usage of it, i suposed that using the latest orbit that comes with 4.25 might do it. 
using only platform is not enough and if those bundles are in the orbit 4.25's means other projects may face the same issue. 

On another hand, do you know why the license check fails ?

**Comment by akurtakov** [comment]
> @akurtakov : i know that the new way is to use maven coordinates in target platform. I can provide a new PR using it in TP, but as it will be the first usage of it, i suposed that using the latest orbit that comes with 4.25 might do it. using only platform is not enough and if those bundles are in the orbit 4.25's means other projects may face the same issue.

So it's hamcrest 2.2 not in Platform repo. It is probably best to switch to maven coordinates as ideally we would stop referencing Orbit at all at some point. Orbit seen almost no changes in the 2022-09 cycle and platform has moved to JUnit 5.9 which is not in Orbit at all.
> 
> On another hand, do you know why the license check fails ?

It's clearlydefined web service not replying. I'll rerun it to check.

**Comment by akurtakov** [comment]
Resolved the conflict but it's unclear tome whether this one is still needed at all.

**Comment by sbouchet** [comment]
> Resolved the conflict but it's unclear tome whether this one is still needed at all.

we're almost here, but integration test still not runs on CI : [1]
```
[INFO] --- tycho-surefire-plugin:3.0.0:test (default-test) @ org.eclipse.linuxtools.docker.integration.tests ---
[INFO] Could not find a java toolchain of type jdk, using java from JAVA_HOME instead (/usr/lib/jvm/java-17-openjdk/bin/java)
[INFO] Executing Test Runtime with timeout 1800, logs (if any) will be placed at: /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/work/data/.metadata/.log
[INFO] Command line:
	[/usr/lib/jvm/java-17-openjdk/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, -Xmx800m, -DsearchConnection=, -DdockerServerURI=, -DunixSocket=, -DdockerHubUsername=, -DdockerHubEmail=, -DdockerHubPassword=, -DdockerComposePath=, -DdockerMockito=true, -DtargetPlatformRepoURL=, -DtargetPlatformFeatureGroupID=, -Dosgi.clean=true, -jar, /home/vnc/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.400.v20210924-0641/org.eclipse.equinox.launcher-1.6.400.v20210924-0641.jar, -data, /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/work/data, -install, /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/work, -configuration, /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/surefire.properties, -product, org.eclipse.platform.ide, -nouithread, -timeout, 1800000]
java.lang.RuntimeException: Bundle org.eclipse.linuxtools.docker.integration.tests is not found
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundle(OsgiSurefireBooter.java:331)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundleClassLoader(OsgiSurefireBooter.java:307)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.createCombinedClassLoader(OsgiSurefireBooter.java:209)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:142)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:49)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] There are test failures.

Please refer to /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/surefire-reports for the individual test results.
```

and log stills says constraints violation from hamcrest: [2] 

```
!SESSION 2022-10-03 08:16:46.301 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.3
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/surefire.properties -product org.eclipse.platform.ide -nouithread -timeout 1800000
Command-line arguments:  -data /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/work/data -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/agent/workspace/linuxtools_master/containers/org.eclipse.linuxtools.docker.integration.tests/target/surefire.properties -product org.eclipse.platform.ide -nouithread -timeout 1800000

!ENTRY org.eclipse.linuxtools.docker.integration.tests 4 0 2022-10-03 08:16:50.247
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.linuxtools.docker.integration.tests [120]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.linuxtools.docker.integration.tests [osgi.identity; osgi.identity="org.eclipse.linuxtools.docker.integration.tests"; type="osgi.bundle"; version:Version="2.2.0.qualifier"; singleton:="true"] because it is exposed to package 'org.hamcrest' from resources org.hamcrest [osgi.identity; osgi.identity="org.hamcrest"; type="osgi.bundle"; version:Version="2.2.0.v20210711-0821"] and org.hamcrest.core [osgi.identity; osgi.identity="org.hamcrest.core"; type="osgi.bundle"; version:Version="1.3.0.v20180420-1519"] via two dependency chains.

Chain 1:
  org.eclipse.linuxtools.docker.integration.tests [osgi.identity; osgi.identity="org.eclipse.linuxtools.docker.integration.tests"; type="osgi.bundle"; version:Version="2.2.0.qualifier"; singleton:="true"]
    import: (osgi.wiring.package=org.hamcrest)
     |
    export: osgi.wiring.package: org.hamcrest
  org.hamcrest [osgi.identity; osgi.identity="org.hamcrest"; type="osgi.bundle"; version:Version="2.2.0.v20210711-0821"]

Chain 2:
  org.eclipse.linuxtools.docker.integration.tests [osgi.identity; osgi.identity="org.eclipse.linuxtools.docker.integration.tests"; type="osgi.bundle"; version:Version="2.2.0.qualifier"; singleton:="true"]
    require: (osgi.wiring.bundle=org.junit)
     |
    provide: osgi.wiring.bundle: org.junit
  org.hamcrest.core [osgi.identity; osgi.identity="org.hamcrest.core"; type="osgi.bundle"; version:Version="1.3.0.v20180420-1519"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.urischeme 4 0 2022-10-03 08:16:59.147
!MESSAGE Cannot run program "xdg-mime": error=2, No such file or directory
!STACK 0
java.io.IOException: Cannot run program "xdg-mime": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.eclipse.urischeme.internal.registration.ProcessExecutor.execute(ProcessExecutor.java:36)
	at org.eclipse.urischeme.internal.registration.RegistrationLinux.getRegisteredDesktopFileForScheme(RegistrationLinux.java:145)
	at org.eclipse.urischeme.internal.registration.RegistrationLinux.determineHandlerLocation(RegistrationLinux.java:87)
	at org.eclipse.urischeme.internal.registration.RegistrationLinux.getSchemesInformation(RegistrationLinux.java:76)
	at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:87)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 7 more

!ENTRY org.eclipse.tycho.surefire.osgibooter 1 0 2022-10-03 08:16:59.241
!MESSAGE starting DumpStackTracesTimer with timeout=1680000 at 2022-10-03 08:16:59 +0000
```

pushed  a tentative fix.

[1] from https://ci.eclipse.org/linuxtools/job/linuxtools/job/master/116/consoleFull
[2] from https://ci.eclipse.org/linuxtools/job/linuxtools/job/master/116/artifact/containers/org.eclipse.linuxtools.docker.integration.tests/target/work/data/.metadata/.log/*view*/

**Comment by jjohnstn** [comment]
Hi Stephane,  I took a shot at getting this to run myself.  I ran into the same problems you did where different version of hamcrest get brought in and ComposeTest doesn't work.  I tried reviving the old docker hamcrest wrapper to get around the latter issue but it didn't work so I ended up ignoring ComposeTest and was able to get the tests running again:  see https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/pull/114

You're welcome to just ignore the test for the time-being or take a look at my patch to see if the hamcrest-wrapper idea might be able to fix the remaining issue and I just didn't do it right.

**Comment by sbouchet** [comment]
> Hi Stephane, I took a shot at getting this to run myself. I ran into the same problems you did where different version of hamcrest get brought in and ComposeTest doesn't work. I tried reviving the old docker hamcrest wrapper to get around the latter issue but it didn't work so I ended up ignoring ComposeTest and was able to get the tests running again: see #114
> 
> You're welcome to just ignore the test for the time-being or take a look at my patch to see if the hamcrest-wrapper idea might be able to fix the remaining issue and I just didn't do it right.

Thanks for taking the time to give a try to fix this. Seems the wrap does not work :( 
I'm also getting similar issues on some JBossTools TestSuite. i'm more in favor to fix composeTest because ignoring it isn't a good idea :D

**Comment by jjohnstn** [comment]
Ok.  I don't know why mockito-core can't find org.hamcrest/SelfDescribing.class.  Perhaps a solution would be to replace the ArgumentMatchers classes used by ComposeTest.

**Comment by sbouchet** [comment]
Fixed Test locally but CI seems stuck. can you check on your side my changes ?

**Comment by akurtakov** [comment]
I'm merging this one . CI gets stuck sometimes.

**Pull request merged**
